### ISSUE TITLE
Dependencies in package.json

### ISSUE THREAD

**Issue by AlexByte** [ctl/lightstamp#2]
Why you haven't added moment.js to dependencies?

**Comment by ctl** [comment]
We have plans to put moment.js off

**Comment by ctl** [comment]
@AlexByte , I think i need to delete this , as [better alternative](http://timeago.org/) is already exist!

**Comment by AlexByte** [comment]
It isn't obligatory to delete 😃

**Comment by ctl** [comment]
@AlexByte, But why should it exist in the presence of a normal alternative?

**Comment by AlexByte** [comment]
In this version, the code is simpler.

**Comment by ctl** [comment]
ok
